name: circle_blast_example
description: Example app for the circle_blast_transition package.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  circle_blast_transition:
    path: ../
